extends RefCounted

static func all_cards() -> Array[Dictionary]:
	return [
		{
			"id": "spark_swarm",
			"name": "星屑群",
			"short_name": "群",
			"role": "数量杂兵",
			"kind": "unit",
			"cost": 2,
			"count": 4,
			"hp": 24.0,
			"damage": 6.0,
			"attack_cooldown": 0.85,
			"range": 1.4,
			"speed": 7.0,
			"radius": 0.75,
			"shape": "circle",
			"color": Color(0.45, 0.83, 0.86),
			"trial_note": "低费多数量，测试场面铺开速度。",
			"task_placeholder": "预留：本局累计存活时间。",
			"evolution_placeholder": "预留：数量分裂方向。"
		},
		{
			"id": "shield_pair",
			"name": "盾卫",
			"short_name": "盾",
			"role": "肉盾杂兵",
			"kind": "unit",
			"cost": 3,
			"count": 2,
			"hp": 92.0,
			"damage": 10.0,
			"attack_cooldown": 1.25,
			"range": 1.5,
			"speed": 4.1,
			"radius": 1.05,
			"shape": "square",
			"color": Color(0.52, 0.70, 0.96),
			"trial_note": "中低费承伤单位，测试抗线价值。",
			"task_placeholder": "预留：替友方承受伤害。",
			"evolution_placeholder": "预留：护盾或嘲讽方向。"
		},
		{
			"id": "cleaver",
			"name": "旋刃兵",
			"short_name": "旋",
			"role": "近战 AOE",
			"kind": "unit",
			"cost": 4,
			"count": 1,
			"hp": 128.0,
			"damage": 18.0,
			"attack_cooldown": 1.45,
			"range": 1.8,
			"speed": 4.4,
			"radius": 1.15,
			"aoe_radius": 3.4,
			"shape": "triangle",
			"color": Color(0.93, 0.70, 0.37),
			"trial_note": "近战范围伤害，测试反杂兵能力。",
			"task_placeholder": "预留：一次攻击命中多个目标。",
			"evolution_placeholder": "预留：扩大范围或附带击退。"
		},
		{
			"id": "quick_archer",
			"name": "连弩手",
			"short_name": "频",
			"role": "频率远程",
			"kind": "unit",
			"cost": 3,
			"count": 1,
			"hp": 54.0,
			"damage": 7.0,
			"attack_cooldown": 0.5,
			"range": 12.0,
			"speed": 3.7,
			"radius": 0.9,
			"shape": "circle",
			"color": Color(0.57, 0.86, 0.54),
			"trial_note": "高频低伤远程，测试持续输出读秒。",
			"task_placeholder": "预留：连续攻击同一目标。",
			"evolution_placeholder": "预留：攻速叠加方向。"
		},
		{
			"id": "ember_mage",
			"name": "秘火手",
			"short_name": "火",
			"role": "伤害远程",
			"kind": "unit",
			"cost": 4,
			"count": 1,
			"hp": 50.0,
			"damage": 24.0,
			"attack_cooldown": 1.45,
			"range": 14.0,
			"speed": 3.1,
			"radius": 0.95,
			"shape": "triangle",
			"color": Color(0.95, 0.43, 0.35),
			"trial_note": "慢频高伤远程，测试爆发换线。",
			"task_placeholder": "预留：击杀低血目标。",
			"evolution_placeholder": "预留：点燃或穿透方向。"
		},
		{
			"id": "arcane_giant",
			"name": "奥术巨像",
			"short_name": "巨",
			"role": "巨型单位",
			"kind": "unit",
			"cost": 6,
			"count": 1,
			"hp": 270.0,
			"damage": 34.0,
			"attack_cooldown": 1.7,
			"range": 2.1,
			"speed": 2.6,
			"radius": 1.8,
			"shape": "square",
			"target_base_only": true,
			"color": Color(0.80, 0.66, 0.96),
			"trial_note": "慢速高血量，只盯基地，测试推进压力。",
			"task_placeholder": "预留：对基地造成伤害。",
			"evolution_placeholder": "预留：攻城或死亡召唤方向。"
		},
		{
			"id": "soul_lance",
			"name": "裂魂矢",
			"short_name": "矢",
			"role": "对单法术",
			"kind": "spell",
			"cost": 3,
			"damage": 82.0,
			"base_damage": 42.0,
			"radius": 4.4,
			"spell_mode": "single",
			"color": Color(0.73, 0.55, 0.95),
			"trial_note": "指定区域内命中最近单体；贴近基地时造成较低基地伤害。",
			"task_placeholder": "预留：用法术击杀关键单位。",
			"evolution_placeholder": "预留：斩杀或回费方向。"
		},
		{
			"id": "starfall",
			"name": "星陨",
			"short_name": "陨",
			"role": "对群法术",
			"kind": "spell",
			"cost": 4,
			"damage": 46.0,
			"base_damage": 24.0,
			"radius": 8.8,
			"spell_mode": "area",
			"color": Color(0.96, 0.82, 0.42),
			"trial_note": "范围伤害，测试清杂兵和压基地的取舍。",
			"task_placeholder": "预留：一次命中多个敌人。",
			"evolution_placeholder": "预留：扩大范围或持续区域。"
		}
	]
