// Auto-generated by tools/balance_studio/server.py. Do not hand-edit.
window.__BALANCE_STUDIO_SOURCE__ = "tools/balance_studio/cards_snapshot.js（离线快照，生成自 游戏工程/data/cards.json）";
window.__BALANCE_STUDIO_DATA__ = {
  "schema_version": 1,
  "updated_at": "2026-08-14",
  "source": "Arcane Frontline V0.3 balance data + 百骸公国_完整卡牌设计",
  "global_rules": {
    "map_long_edge_logic_units": 100,
    "unit_radius_scale": 2.0,
    "mana_per_second": 0.5,
    "mana_max": 10.0,
    "base_hp": 300.0
  },
  "field_definitions": {
    "cost": {
      "label": "费用",
      "unit": "点法力",
      "applies_to": "全部卡牌",
      "notes": "部署单位或施放法术时一次性消耗。当前费用上限为 10 点。"
    },
    "count": {
      "label": "生成数量",
      "unit": "个单位",
      "applies_to": "生物",
      "notes": "每次使用该生物卡时生成的单位数量。"
    },
    "hp": {
      "label": "生命",
      "unit": "点",
      "applies_to": "生物",
      "notes": "单个单位的最大生命值，不是整张卡的总生命值。整卡总生命 = hp * count。"
    },
    "damage": {
      "label": "攻击力/法术伤害",
      "unit": "点",
      "applies_to": "全部卡牌",
      "notes": "生物为每次普攻伤害；法术为对单位伤害。"
    },
    "base_damage": {
      "label": "基地伤害",
      "unit": "点",
      "applies_to": "法术",
      "notes": "法术命中基地时造成的伤害。生物攻击基地仍使用 damage。"
    },
    "attack_cooldown": {
      "label": "攻击间隔",
      "unit": "秒/次",
      "applies_to": "生物",
      "notes": "越小攻击越快。单体 DPS = damage / attack_cooldown。"
    },
    "range": {
      "label": "射程",
      "unit": "逻辑单位",
      "applies_to": "生物",
      "notes": "地图长边为 100 个逻辑单位；速度和距离都使用该尺度。"
    },
    "speed": {
      "label": "移动速度",
      "unit": "逻辑单位/秒",
      "applies_to": "生物",
      "notes": "速度 1 表示每秒移动 1 个逻辑单位。"
    },
    "radius": {
      "label": "半径",
      "unit": "逻辑单位",
      "applies_to": "生物和法术",
      "notes": "生物这里填写基础半径，实战碰撞/表现半径 = radius * unit_radius_scale；法术范围不乘倍率。"
    },
    "aoe_radius": {
      "label": "范围伤害半径",
      "unit": "逻辑单位",
      "applies_to": "生物攻击或进化效果",
      "notes": "攻击落点或光环效果的范围伤害半径。"
    },
    "aura_interval": {
      "label": "光环间隔",
      "unit": "秒/次",
      "applies_to": "进化生物",
      "notes": "光环触发频率。光环 DPS = aura_damage / aura_interval。"
    },
    "aura_radius": {
      "label": "光环半径",
      "unit": "逻辑单位",
      "applies_to": "进化生物",
      "notes": "以单位当前位置为中心的周期范围效果半径。"
    },
    "aura_damage": {
      "label": "光环伤害",
      "unit": "点",
      "applies_to": "进化生物",
      "notes": "每次光环触发时造成的伤害。"
    },
    "multi_target_count": {
      "label": "同时攻击目标数",
      "unit": "个目标",
      "applies_to": "进化生物",
      "notes": "用于估算理想多目标 DPS；实际收益取决于可命中的敌人数量。"
    },
    "spell_mode": {
      "label": "法术模式",
      "unit": "枚举",
      "applies_to": "法术",
      "notes": "single 为范围内最近单体，area 为范围伤害，line 为路径伤害。"
    },
    "projectile_travel_time": {
      "label": "弹道飞行时间",
      "unit": "秒",
      "applies_to": "带弹道的法术",
      "notes": "大于 0 时从施法方基地飞向目标点，并在抵达后结算法术；0 或未设置时即时结算。"
    },
    "deckable": {
      "label": "玩家可携带",
      "unit": "布尔值",
      "applies_to": "全部卡牌与衍生单位",
      "notes": "默认为 true；显式设为 false 时仍保留在图鉴与运行时目录，但不会进入玩家牌组仓库、牌组存档或出战牌组。"
    },
    "ai_deckable": {
      "label": "Bot 可携带",
      "unit": "布尔值",
      "applies_to": "可携带卡",
      "notes": "默认为 true；显式设为 false 时，Bot 的随机与固定牌组入口都会过滤该卡。"
    },
    "play_cooldown": {
      "label": "出牌冷却",
      "unit": "秒",
      "applies_to": "有内置冷却的卡牌",
      "notes": "成功使用后，同一阵营在倒计时结束前不能再次使用同一基础卡；进化前后共享基础卡 id 与冷却。"
    },
    "max_mana_refund": {
      "label": "单次施放最大回费",
      "unit": "点法力",
      "applies_to": "回费区域法术",
      "notes": "每个独立施放区域累计能实际加入法力条的费用上限；满费时的溢出不计入累计。"
    }
  },
  "cards": [
    {
      "id": "spark_swarm",
      "name": "星屑群",
      "short_name": "群",
      "role": "数量杂兵",
      "kind": "unit",
      "cost": 2,
      "count": 4,
      "hp": 24.0,
      "damage": 6.0,
      "attack_cooldown": 0.85,
      "range": 1.4,
      "speed": 7.0,
      "radius": 0.75,
      "shape": "circle",
      "color": "#73d4db",
      "trial_note": "低费多数量，测试场面铺开速度。",
      "task": {
        "type": "card_play_count",
        "summary": "本局中打出过三次星屑群。",
        "progress_label": "星屑群",
        "watch_card_id": "spark_swarm",
        "target": 3
      },
      "evolution": {
        "id": "spark_drift",
        "name": "星屑漂流",
        "short_name": "漂",
        "summary": "数量变为 6，其余效果属性不变。",
        "overrides": {
          "count": 6
        }
      }
    },
    {
      "id": "shield_pair",
      "name": "盾卫",
      "short_name": "盾",
      "role": "肉盾杂兵",
      "kind": "unit",
      "cost": 3,
      "count": 2,
      "hp": 92.0,
      "damage": 10.0,
      "attack_cooldown": 1.25,
      "range": 1.5,
      "speed": 4.1,
      "radius": 1.05,
      "shape": "square",
      "color": "#85b3f5",
      "trial_note": "中低费承伤单位，测试抗线价值。",
      "task": {
        "type": "unit_hp_below_ratio",
        "summary": "当前血量低于 2/3。",
        "progress_label": "低血",
        "watch_card_id": "shield_pair",
        "target": 1,
        "hp_ratio": 0.6667
      },
      "evolution": {
        "id": "steadfast_guard",
        "name": "坚盾护卫",
        "short_name": "坚",
        "summary": "生命值翻倍，其余效果属性不变。",
        "overrides": {
          "hp": 184.0
        }
      }
    },
    {
      "id": "cleaver",
      "name": "旋刃兵",
      "short_name": "旋",
      "role": "近战 AOE",
      "kind": "unit",
      "cost": 4,
      "count": 1,
      "hp": 128.0,
      "damage": 25.0,
      "attack_cooldown": 1.8,
      "range": 1.5,
      "speed": 4.4,
      "radius": 1.15,
      "multi_target_count": 20,
      "shape": "triangle",
      "color": "#edb35e",
      "trial_note": "近战范围伤害，测试反杂兵能力。",
      "task": {
        "type": "card_kill_count",
        "summary": "所有旋刃兵在本局中总共杀死超过 12 个敌人。",
        "progress_label": "击杀",
        "watch_card_id": "cleaver",
        "target": 13,
        "target_text": ">12"
      },
      "evolution": {
        "id": "wheel_blade",
        "name": "轮刃兵",
        "short_name": "轮",
        "summary": "攻击间隔减少到 1.4 秒，射程提升到 2.5。",
        "overrides": {
          "attack_cooldown": 1.4,
          "range": 2.5
        }
      }
    },
    {
      "id": "quick_archer",
      "name": "连弩手",
      "short_name": "频",
      "role": "频率远程",
      "kind": "unit",
      "cost": 3,
      "count": 1,
      "hp": 54.0,
      "damage": 7.0,
      "attack_cooldown": 0.5,
      "range": 12.0,
      "speed": 3.7,
      "radius": 0.9,
      "shape": "circle",
      "color": "#91db8a",
      "trial_note": "高频低伤远程，测试持续输出读秒。",
      "task": {
        "type": "card_play_burst",
        "summary": "3 秒钟内使用 3 个连弩手。",
        "progress_label": "连发",
        "watch_card_id": "quick_archer",
        "target": 3,
        "window": 3.0
      },
      "evolution": {
        "id": "roaming_archer",
        "name": "漫游弓手",
        "short_name": "游",
        "summary": "一次攻击同时攻击两个敌对目标。",
        "overrides": {
          "multi_target_count": 2
        }
      }
    },
    {
      "id": "ember_mage",
      "name": "秘火手",
      "short_name": "火",
      "role": "伤害远程",
      "kind": "unit",
      "cost": 4,
      "count": 1,
      "hp": 50.0,
      "damage": 24.0,
      "attack_cooldown": 1.45,
      "range": 14.0,
      "speed": 3.1,
      "radius": 0.95,
      "shape": "triangle",
      "color": "#f26e59",
      "trial_note": "慢频高伤远程，测试爆发换线。",
      "task": {
        "type": "single_unit_kill_count",
        "summary": "一名秘火手击杀 3 名敌人。",
        "progress_label": "单体击杀",
        "watch_card_id": "ember_mage",
        "target": 3
      },
      "evolution": {
        "id": "fire_thrower",
        "name": "投火手",
        "short_name": "投",
        "summary": "攻击落点附带半径为 2 的 AOE。",
        "overrides": {
          "aoe_radius": 2.0
        }
      }
    },
    {
      "id": "arcane_giant",
      "name": "奥术巨像",
      "short_name": "巨",
      "role": "巨型单位",
      "kind": "unit",
      "cost": 6,
      "count": 1,
      "hp": 270.0,
      "damage": 34.0,
      "attack_cooldown": 1.7,
      "range": 2.1,
      "speed": 2.6,
      "radius": 1.8,
      "shape": "square",
      "target_base_only": true,
      "color": "#cca8f5",
      "trial_note": "慢速高血量，只盯基地，测试推进压力。",
      "task": {
        "type": "mana_reached",
        "summary": "拥有 10 点法力。",
        "progress_label": "法力",
        "target": 10
      },
      "evolution": {
        "id": "arcane_power_giant",
        "name": "奥能巨像",
        "short_name": "能",
        "summary": "基础半径变为 2；每 0.6 秒对 2.1 范围内造成 6 点 AOE 伤害。",
        "overrides": {
          "radius": 2.0,
          "aura_interval": 0.6,
          "aura_radius": 2.1,
          "aura_damage": 6.0
        }
      }
    },
    {
      "id": "soul_lance",
      "name": "裂魂矢",
      "short_name": "矢",
      "role": "对单法术",
      "kind": "spell",
      "cost": 3,
      "damage": 82.0,
      "base_damage": 33.0,
      "radius": 4.4,
      "spell_mode": "single",
      "projectile_travel_time": 1.0,
      "color": "#ba8cf2",
      "trial_note": "从己方基地发射弹道，1 秒后抵达指定区域并命中最近单体；贴近基地时造成较低基地伤害。",
      "task": {
        "type": "base_hit_count",
        "summary": "用裂魂矢攻击三次敌方基底。",
        "progress_label": "攻基",
        "watch_card_id": "soul_lance",
        "target": 3
      },
      "evolution": {
        "id": "sky_rift_arrow",
        "name": "裂天矢",
        "short_name": "天",
        "summary": "费用变为 5；改为即时路径法术，不再保留 1 秒弹道；对己方基地到目标点路径上所有单位和基地造成伤害，己方基地也会被路径命中。",
        "overrides": {
          "cost": 5,
          "spell_mode": "line",
          "projectile_travel_time": 0.0
        }
      }
    },
    {
      "id": "starfall",
      "name": "星陨",
      "short_name": "陨",
      "role": "对群法术",
      "kind": "spell",
      "cost": 4,
      "damage": 46.0,
      "base_damage": 24.0,
      "radius": 8.8,
      "spell_mode": "area",
      "projectile_travel_time": 1.0,
      "color": "#f5d166",
      "trial_note": "从己方基地发射弹道，1 秒后抵达目标点造成范围伤害，测试清杂兵和压基地的取舍。",
      "task": {
        "type": "linked_card_play_count",
        "summary": "使用 3 次星屑群。",
        "progress_label": "星屑群",
        "watch_card_id": "spark_swarm",
        "target": 3
      },
      "evolution": {
        "id": "star_scatter",
        "name": "星散",
        "short_name": "散",
        "summary": "继承 1 秒弹道；范围半径扩大到 12。",
        "overrides": {
          "radius": 12.0
        }
      }
    },
    {
      "id": "timid_squire",
      "name": "胆怯侍从",
      "short_name": "侍",
      "role": "侍童远程",
      "kind": "unit",
      "faction": "百骸公国",
      "cost": 3,
      "count": 1,
      "hp": 90.0,
      "damage": 8.0,
      "attack_cooldown": 1.2,
      "range": 9.0,
      "speed": 4.5,
      "radius": 0.9,
      "shape": "diamond",
      "color": "#a9b8c6",
      "entry_summons": [
        {
          "unit_id": "book_squire",
          "count": 1,
          "formation": "behind"
        }
      ],
      "trial_note": "百骸公国试调数值；登场时在身后召唤 1 名书卷侍童。",
      "task": {
        "type": "squire_death_count",
        "summary": "己方书卷侍童全局阵亡 3 名。",
        "progress_label": "书卷阵亡",
        "watch_unit_id": "book_squire",
        "target": 3
      },
      "evolution": {
        "id": "roaming_squire",
        "name": "游走侍从",
        "short_name": "游",
        "summary": "费用变为 4，攻击提升至中等；经过桥梁时再召唤 1 名书卷侍童。",
        "overrides": {
          "cost": 4,
          "damage": 18.0,
          "bridge_summons": [
            {
              "unit_id": "book_squire",
              "count": 1,
              "formation": "behind"
            }
          ]
        }
      }
    },
    {
      "id": "banner_knight",
      "name": "方旗骑士",
      "short_name": "旗",
      "role": "侍童成长前排",
      "kind": "unit",
      "faction": "百骸公国",
      "cost": 5,
      "count": 1,
      "hp": 180.0,
      "damage": 18.0,
      "attack_cooldown": 1.2,
      "range": 1.7,
      "speed": 4.2,
      "radius": 1.1,
      "aoe_radius": 2.4,
      "shape": "square",
      "color": "#8795a8",
      "squire_death_buff": {
        "radius": 13.0,
        "max_stacks": 3,
        "damage_percent": 25,
        "cooldown_percent": 10,
        "damage_reduction_percent": 10
      },
      "trial_note": "百骸公国试调数值；附近己方侍童阵亡时获得最多 3 层线性成长。",
      "task": {
        "type": "single_unit_kill_count",
        "summary": "同一名方旗骑士击杀 3 名敌人。",
        "progress_label": "单体击杀",
        "watch_card_id": "banner_knight",
        "target": 3
      },
      "evolution": {
        "id": "banner_knight_captain",
        "name": "方旗骑士长",
        "short_name": "长",
        "summary": "登场时在两翼召唤 2 名书卷侍童，保留成长能力。",
        "overrides": {
          "entry_summons": [
            {
              "unit_id": "book_squire",
              "count": 2,
              "formation": "flanks"
            }
          ]
        }
      }
    },
    {
      "id": "grand_cross_knight",
      "name": "大十字骑士",
      "short_name": "十",
      "role": "侍童光环巨型单位",
      "kind": "unit",
      "faction": "百骸公国",
      "cost": 8,
      "count": 1,
      "hp": 360.0,
      "damage": 34.0,
      "attack_cooldown": 2.0,
      "range": 2.0,
      "speed": 3.8,
      "radius": 1.7,
      "target_base_only": true,
      "shape": "hexagon",
      "color": "#6f7f92",
      "entry_summons": [
        {
          "unit_id": "book_squire",
          "count": 3,
          "formation": "behind"
        }
      ],
      "squire_aura": {
        "radius": 12.0,
        "book_cooldown_percent": 5,
        "sword_speed_percent": 5,
        "dawn_damage_percent": 5
      },
      "trial_note": "百骸公国试调数值；仅攻击建筑，附近三类侍童实时提供无上限线性光环。",
      "task": {
        "type": "squire_simultaneous",
        "summary": "己方场上同时存在 9 名侍童。",
        "progress_label": "在场侍童",
        "target": 9
      },
      "evolution": {
        "id": "grand_cross_knight_order",
        "name": "大十字骑士团",
        "short_name": "团",
        "summary": "改为默认索敌；附近侍童受伤转移给本单位，且移速与本单位同步。",
        "overrides": {
          "target_base_only": false,
          "protect_squires": true,
          "protection_radius": 12.0,
          "sync_squire_speed": true
        }
      }
    },
    {
      "id": "pipe_network_knight",
      "name": "管网骑士",
      "short_name": "管",
      "role": "持续召唤者",
      "kind": "unit",
      "faction": "百骸公国",
      "cost": 6,
      "count": 1,
      "hp": 100.0,
      "damage": 10.0,
      "attack_cooldown": 1.2,
      "range": 1.5,
      "speed": 2.8,
      "radius": 1.1,
      "shape": "diamond",
      "color": "#758c94",
      "entry_summons": [
        {
          "unit_id": "sword_squire",
          "count": 1,
          "formation": "random_near"
        }
      ],
      "periodic_summon": {
        "unit_id": "sword_squire",
        "count": 1,
        "interval": 6.0,
        "formation": "random_near"
      },
      "trial_note": "百骸公国试调数值；登场与每 6 秒召唤 1 名持剑侍童。",
      "task": {
        "type": "squire_summon_count",
        "summary": "己方全局累计召唤 6 名侍童。",
        "progress_label": "侍童召唤",
        "target": 6
      },
      "evolution": {
        "id": "pipe_network_knight_captain",
        "name": "管网骑士长",
        "short_name": "网",
        "summary": "登场时额外召唤 1 名启明侍童。",
        "overrides": {
          "entry_summons": [
            {
              "unit_id": "sword_squire",
              "count": 1,
              "formation": "random_near"
            },
            {
              "unit_id": "dawn_squire",
              "count": 1,
              "formation": "random_near"
            }
          ]
        }
      }
    },
    {
      "id": "waterway_knight",
      "name": "水脉骑士",
      "short_name": "水",
      "role": "侍童成长远程",
      "kind": "unit",
      "faction": "百骸公国",
      "cost": 4,
      "count": 1,
      "hp": 65.0,
      "damage": 32.0,
      "attack_cooldown": 1.8,
      "range": 15.0,
      "speed": 2.8,
      "radius": 0.95,
      "shape": "triangle",
      "color": "#77a9ba",
      "squire_death_buff": {
        "radius": 18.0,
        "max_stacks": 3,
        "damage_percent": 5,
        "range_percent": 10
      },
      "trial_note": "百骸公国试调数值；附近己方侍童阵亡时获得最多 3 层射程与攻击成长。",
      "task": {
        "type": "squire_death_count",
        "summary": "己方侍童全局阵亡 6 名。",
        "progress_label": "侍童阵亡",
        "target": 6
      },
      "evolution": {
        "id": "waterway_knight_captain",
        "name": "水脉骑士长",
        "short_name": "潮",
        "summary": "登场时在身后召唤 2 名持剑侍童。",
        "overrides": {
          "entry_summons": [
            {
              "unit_id": "sword_squire",
              "count": 2,
              "formation": "behind"
            }
          ]
        }
      }
    },
    {
      "id": "apprentice_knight_recruitment",
      "name": "见习骑士征召",
      "short_name": "征",
      "role": "全图侍童召唤",
      "kind": "spell",
      "faction": "百骸公国",
      "deckable": false,
      "cost": 4,
      "damage": 0.0,
      "base_damage": 0.0,
      "radius": 2.0,
      "spell_mode": "summon",
      "summon_unit_id": "dawn_squire",
      "summon_count": 1,
      "summon_formation": "center",
      "color": "#e2c878",
      "trial_note": "当前因强度过高被禁用，无法编入牌组；卡牌仍保留在图鉴中。原效果为在全图目标点召唤启明侍童。",
      "task": {
        "type": "squire_summon_count",
        "summary": "己方全局累计召唤 6 名侍童。",
        "progress_label": "侍童入场",
        "target": 6
      },
      "evolution": {
        "id": "apprentice_knight_assembly",
        "name": "见习骑士集结",
        "short_name": "集",
        "summary": "敌方半场召唤 1 名，己方半场召唤 2 名启明侍童。",
        "overrides": {
          "own_half_summon_count": 2
        }
      }
    },
    {
      "id": "little_knight_order",
      "name": "小小骑士团",
      "short_name": "小",
      "role": "己方铺场召唤",
      "kind": "spell",
      "faction": "百骸公国",
      "cost": 3,
      "damage": 0.0,
      "base_damage": 0.0,
      "radius": 3.0,
      "spell_mode": "summon",
      "summon_unit_id": "sword_squire",
      "summon_count": 3,
      "summon_formation": "triangle",
      "cast_own_half_only": true,
      "color": "#bdc5cc",
      "trial_note": "百骸公国试调数值；仅可在己方半场以三角阵召唤 3 名持剑侍童。",
      "task": {
        "type": "squire_summon_count",
        "summary": "己方全局累计召唤 9 名侍童。",
        "progress_label": "侍童召唤",
        "target": 9
      },
      "evolution": {
        "id": "little_knights_knight_order",
        "name": "小小骑士骑士团团",
        "short_name": "团",
        "summary": "首次召唤后 3 秒，在原目标点再召唤 3 名持剑侍童。",
        "overrides": {
          "delayed_summon_delay": 3.0,
          "delayed_summon_count": 3
        }
      }
    },
    {
      "id": "one_bone_heart",
      "name": "百骸一心",
      "short_name": "心",
      "role": "阵亡回费法术",
      "kind": "spell",
      "faction": "百骸公国",
      "cost": 2,
      "damage": 0.0,
      "base_damage": 0.0,
      "radius": 10.0,
      "spell_mode": "death_mana_zone",
      "duration": 6.0,
      "include_enemy_deaths": false,
      "play_cooldown": 10.0,
      "max_mana_refund": 10.0,
      "ai_deckable": false,
      "color": "#9b84bd",
      "trial_note": "百骸公国试调数值；仅玩家可编入牌组，Bot 不携带；内置冷却 10 秒；每次施放的区域最多实际回复 10 点法力；6 秒内区域中每有 1 名己方单位阵亡回复 1 点法力，同玩家重叠区域不重复结算。",
      "task": {
        "type": "all_unit_death_count",
        "summary": "全局双方累计阵亡 100 名单位。",
        "progress_label": "全场阵亡",
        "target": 100
      },
      "evolution": {
        "id": "ten_thousand_bone_heart",
        "name": "万骸一心",
        "short_name": "万",
        "summary": "继承 10 秒内置冷却和单次施放最多回复 10 点法力的上限；改为监听区域内任意阵营单位阵亡。",
        "overrides": {
          "include_enemy_deaths": true
        }
      }
    }
  ],
  "derivative_units": [
    {
      "id": "book_squire",
      "name": "书卷侍童",
      "short_name": "书",
      "role": "衍生侍童（不可携带）",
      "kind": "unit",
      "faction": "百骸公国",
      "deckable": false,
      "cost": 1,
      "count": 1,
      "hp": 34.0,
      "damage": 8.0,
      "attack_cooldown": 1.2,
      "range": 1.3,
      "speed": 4.5,
      "radius": 0.65,
      "target_base_only": true,
      "tags": [
        "squire",
        "book_squire",
        "derivative"
      ],
      "on_death": {
        "mana_gain": 1
      },
      "shape": "circle",
      "color": "#b9c7d0",
      "trial_note": "衍生单位，不可编入牌组；阵亡时为所属玩家回复 1 点法力。"
    },
    {
      "id": "sword_squire",
      "name": "持剑侍童",
      "short_name": "剑",
      "role": "衍生侍童（不可携带）",
      "kind": "unit",
      "faction": "百骸公国",
      "deckable": false,
      "cost": 1,
      "count": 1,
      "hp": 18.0,
      "damage": 8.0,
      "attack_cooldown": 0.65,
      "range": 1.2,
      "speed": 7.5,
      "radius": 0.6,
      "target_base_only": true,
      "tags": [
        "squire",
        "sword_squire",
        "derivative"
      ],
      "shape": "triangle",
      "color": "#d7dde2",
      "trial_note": "衍生单位，不可编入牌组；高攻速、高移速，仅攻击建筑。"
    },
    {
      "id": "dawn_squire",
      "name": "启明侍童",
      "short_name": "明",
      "role": "衍生爆破侍童（不可携带）",
      "kind": "unit",
      "faction": "百骸公国",
      "deckable": false,
      "cost": 3,
      "count": 1,
      "hp": 40.0,
      "damage": 10.0,
      "attack_cooldown": 1.8,
      "range": 1.3,
      "speed": 4.5,
      "radius": 0.75,
      "target_base_only": true,
      "tags": [
        "squire",
        "dawn_squire",
        "derivative"
      ],
      "on_death": {
        "explosion_radius": 6.0,
        "explosion_damage": 30,
        "explosion_base_damage": 60,
        "fire_duration": 3.0,
        "fire_tick_interval": 0.5,
        "fire_damage": 5,
        "fire_base_damage": 2
      },
      "shape": "hexagon",
      "color": "#e0b85e",
      "trial_note": "衍生单位，不可编入牌组；阵亡时造成半径 6 爆炸，并留下持续 3 秒的火焰区域。"
    }
  ]
};
